language: python

python:
  - "2.7"

env:
  global:
    - PYTHONPATH=".:test"
  matrix:
    - DJANGO="Django>=1.6,<1.7"
    - DJANGO="Django>=1.7,<1.8"
    - DJANGO="Django>=1.8,<1.9"
    - DJANGO="Django>=1.9,<1.10"

install:
  - pip install -e .
  - pip install -e ".[test]"
  - pip install -q $DJANGO
  - pip install coveralls
  - setenv

script:
  - py.test --cov=eulcommon

after_success:
  - coveralls
